version: '3.7'
services:
    motoring-meter-api:
        build: 
            context: ./motoring-meter-api
            dockerfile: Dockerfile
        volumes:
            - ./motoring-meter-api:/usr/src/app
            - /usr/src/app/node_modules
        networks: 
            - motoring-meter-dev-net
        ports:
            - "3001:3001"
    motoring-meter-ui:
        build: 
            context: ./motoring-meter-ui
            dockerfile: Dockerfile
        volumes:
            - ./motoring-meter-ui:/usr/src/app:rw
            - /usr/src/app/node_modules
        networks: 
            - motoring-meter-dev-net
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://localhost:3001
        ports:
            - "3000:3000"
networks: 
    motoring-meter-dev-net:
        name: motoring-meter-dev-net